layout: default
url: "https://onedeshiza.github.io"
baseurl: "/game_woven-scroll"
defaults:
  - scope:
      path: ""
    values:
      layout: default
markdown: kramdown
theme: jekyll-theme-slate
lang: ja
include:
  - asset/css
plugins:
  - jekyll-include-cache
show_downloads: false
github:
  is_project_page: false
