---
layout: default
---

title: わんでし座
description: フリーゲーム製作所

url: "https://onedeshiza.github.io"
baseurl: "/game_woven-scroll"

defaults:
  - scope:
      path: ""
    values:
    
markdown: kramdown
theme: jekyll-theme-slate
lang: ja
include:
  - assets/css
plugins:
  - jekyll-include-cache
show_downloads: false
github:
  is_project_page: false
